server:
    port: 9000

db:
    location: 0.0.0.0

spring:
    application:
        name: micro-person
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${db.location}:5555/person
        username: toy
        password: toy
    # servlet:
    #     multipart:
    #         max-file-size: 50MB